language: go
install: make
sudo: required
services:
- docker
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export REPO=ottoyiu/k8s-ec2-srcdst
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- make push_image
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: or4vHnrTLAF36IVgzk9iHL43GQT6QkU+98FBpeArgIuxFpo0438WkaIE244553DCp5xf2YwjSyNA1+3u74eiywSgcYpikbnwWlDCpKjtJVIxmY18xdIqHDeisEGyV2GVfI7y5HwJCAfs8vbw7+uZ+2siyWSZ4r5VUGiGMyuAAcDvXBnGvbuPeuWShUmocMnuFQ9VTTJe/41mUAIRZ6bQH7BkWWZfCJibHHH8CiMFWWdcwBFqHpTiqfzfCayZAHqukh6+w+YfBGkIefgPB68KP5JXBVQVXvXKEDx6DGBbZ8CWLHOhGKvTD6w4rR0aYso9UXtmQoMhUSnJ5oDmtdoQmhPNskLKVLfCq8BaycfuCLn7izYkVn0ma3sa2zt4vQ57gxMA/fQPmMuaVpiasJQQwUXvv3tO6FwlQzZ9T5NqG1Ds067uFzgSg5+TrKQ//aFiO2aY7J+0QlJMp2BZrTFirmsNYpWVTYVss0U0OB0giibBK38F/B6VtUkVS0QwoE3ZUqPawpAbCQLjR/TUBO+9w9S6bDI739X/lDdnJQJ/4pN8mNstFrktrIk46LqSm9ob6sL2NOwJ+bCa4b6lx2v5qOeUhCM1tY4LHjZcCh3xpkGFVEQ9AIVSe6kcva0LmIEL4gCRbm3J3RWUWpPJWedDvvSOoWliRK81jPsPEPY/gCk=
  - secure: LDq8yIbwEZUZjqeqgcx8iAuasf8LWUmeof+C141Ch/EaGwTqCK94KPE7lcF9nRaaKztsfOCMDIpVi+Ko9z+crtbKLAYGdDJzEpMH+nYjikihg+q1MmDNB++OtsQgEm4BB7ps77jqz9wwY9CIkte3Jev+7AEgnBV5x4zpPSvU13N56S2NJeROdJy8SOZmKJ8Dpa78tBxo+SJk6HKKPumdaDgAMhRmmQJP4yg8IfvErVhdu2zokRefn69sk8dw4z2zBmHHZ0pjj8mOoBZWiVR+6h6ZrzXKAH2WNELng2MAULX3szP0sGfmYnlRREu24UsT7f1HsSANuAoY35wFB0YoAhhWOtlMSiBqOD79coVe54kqIef4wkwNF1qFasrlnyUofx7K455W8Y0nxnrIG9yG+XkObRIkaJBhdrAue+6NRtytNd/ijUPa7IhNYRePPPlG9dnL4zJW1g6fY7gAjoAbOvC/rdj3JpoOPmRoiK7Ng1STUXFkZvT6VZ9ARTDaVNhYVWIomPwHh1qPyps5EZcf3/vhS2OasmwvOdPRYKUlDHGs9hMrhn7ZsfaZg04vhzGAskvbLvw4STOaI3JcwfDdl+D52ph+QZP+uOhC2trgYFUlE8xDOPRjRLzka71UOypvC41CFLUGrB+avyv0L2Q/FY3p22QEcttynqe9XSft7pE=
  - secure: PzMHXjNkFcApP6KRAKKBjwfKR0HVrxA/kwjA0tAHVqpZwel+PKm7JPXc0jYNxJoij4gHjA7o48LdJs/83VciomPaUWngI9efHoXPSggSwTa5GyE24jzYShN9Owsq/pW7bdSFHvGOvrmXKWmi/bIIp2k9BTvSwF/jz4iVVhq+VTN0sCdUw2DxN0HZx/cLBIRkDX87pzesG8n0NqgTKrBIPNRrwr6uFFGhi9BPwh8BEIFm3kEcPPG3U2gYkOMDRapUDgD6YaalXkCsBi20pYzAAaGKW/wklQhnPGQXWxUo4nhWuXuXoTNLd7BRh6Ygc/WCFmqEeC0RQ5gscqBK4V7hpDx2LdUgoVBLMvPaMXVbAoxAhCbKlG1IhPCnXlbcbgFUTHuPLFIjeNQGjOgzUr/eOdcm2ruLRzrGd5yvyglt9uL9au+Ac3KbnJGp95V0IP3QKzI9zRYPlxLBQ/M7T/zjrQfQa1BRq+alssNdNHs1kESItcWvsK7wgqGkvzRVrK95O0senzNS2oRY9DF8cEOpvm7ljlHw35wBgZYYXei6cnXFlp5yGV3iSKguiswSeTqCWK2bb5kSJv9wUwlxDVbvulBuqT1h8q837hHYuNrKO+9znWmumFssg4o6jI4srny2hZbcav+O0MA9jxvW/tJubz17KSdttIYj681B6G4Zjl0=
